# permissions for end users to edit mirakuruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mirakurun-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: yumemi
    app.kubernetes.io/part-of: yumemi
    app.kubernetes.io/managed-by: kustomize
  name: mirakurun-editor-role
rules:
- apiGroups:
  - yumemi.sinoa.jp
  resources:
  - mirakuruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yumemi.sinoa.jp
  resources:
  - mirakuruns/status
  verbs:
  - get
